const express = require("express")
const userRoute = require("./user.routes")
const uploadRoute = require("./upload.route")
const cartRoute = require("./cart.routes")
const wishlistRoute = require("./wishlist.routes")
const bannerRoute = require("./banner.route")
const subCategoryRoute = require("./getSubCategory.route")
const parentCategoryRoute = require("./getParentCategory.route")
const reviewRoute = require("./review.routes")
const searchRoute = require("./search.route")
const homeRoute = require("./home.route")
const offerRoute = require("./offer.route")
const mergeRoute = require("./merge.route")
const categoryRoute = require("./category.route")

let routes = express.Router()

routes.use("/user", userRoute)
routes.use("/upload", uploadRoute)
routes.use("/cart", cartRoute)
routes.use("/wishlist", wishlistRoute)
routes.use("/banner", bannerRoute)
routes.use("/subCategory", subCategoryRoute)
routes.use("/getSub&ParentCategory", parentCategoryRoute)
routes.use("/review", reviewRoute)
routes.use("/search", searchRoute)
routes.use("/home", homeRoute)
routes.use("/offer", offerRoute)
routes.use("/merge", mergeRoute)
routes.use("/category", categoryRoute)

module.exports = routes